name: Verification
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install package
        run: pip install -e.'[testing]'
      - name: unit tests
        run: 
          rake units
