name: Verification
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: install testix (editable mode + testing support)
        run: pip install -e.'[testing]'
      - name: unit tests
        run: 
          rake units
